# Generated by Django 5.1.3 on 2025-04-03 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_rename_order_payment_payment_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='firstname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='lastname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
