# Generated by Django 5.1.3 on 2025-02-27 11:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_rename_name_product_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.FloatField(null=True)),
                ('height', models.FloatField(null=True)),
                ('dimension_unit', models.CharField(choices=[('inches', 'Inches'), ('feet', 'Feet')], default='inches', max_length=10)),
                ('design_file', models.ImageField(null=True, upload_to='print_jobs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])])),
                ('special_instructions', models.TextField(blank=True)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('date_ordered', models.DateTimeField(auto_now_add=True)),
                ('complete', models.BooleanField(default=False)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.customer')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
        ),
    ]
