# Generated by Django 5.1.3 on 2025-02-27 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_pendingorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSpecField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('field_type', models.CharField(choices=[('text', 'Text Input'), ('number', 'Number Input'), ('select', 'Select Dropdown'), ('file', 'File Upload'), ('color', 'Color Picker'), ('textarea', 'Text Area')], max_length=20)),
                ('required', models.BooleanField(default=True)),
                ('help_text', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('options', models.TextField(blank=True, help_text='For select fields, enter options separated by commas', null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spec_fields', to='store.product')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
