# Generated by Django 5.1.3 on 2025-02-27 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_productvariant'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='product_variant/'),
        ),
    ]
