# Generated by Django 5.1.3 on 2025-02-27 15:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_productvariant_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('field_value', models.TextField(blank=True, null=True)),
                ('field_file', models.FileField(blank=True, null=True, upload_to='order_specs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])])),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='store.order')),
            ],
        ),
        migrations.CreateModel(
            name='PendingOrderSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('field_value', models.TextField(blank=True, null=True)),
                ('field_file', models.FileField(blank=True, null=True, upload_to='pending_specs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])])),
                ('pending_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='store.pendingorder')),
            ],
        ),
    ]
