# Generated by Django 5.1.3 on 2025-02-27 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_orderspecification_pendingorderspecification'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingorderspecification',
            name='spec_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.productspecfield'),
        ),
    ]
