# Generated by Django 5.1.3 on 2025-03-02 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_pendingorderspecification_spec_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='base_price',
        ),
    ]
