# Generated by Django 5.1.3 on 2025-03-02 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_rename_price_product_base_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingorder',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.productvariant'),
        ),
    ]
