# Generated by Django 5.1.3 on 2025-03-13 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_pendingorder_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingorder',
            name='designer_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pendingorder',
            name='designer_instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pendingorder',
            name='order_type',
            field=models.CharField(choices=[('print', 'Print Only'), ('designer', 'Hire Designer')], default='print', max_length=20),
        ),
        migrations.CreateModel(
            name='ReferenceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='reference_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('pending_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_images', to='store.pendingorder')),
            ],
        ),
    ]
