# Generated by Django 5.1.3 on 2025-03-14 11:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_pendingorder_designer_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingorder',
            name='design_file',
            field=models.ImageField(blank=True, null=True, upload_to='print_jobs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='pendingorder',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pendingorder',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='pendingorder',
            name='width',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
