# Generated by Django 5.1.3 on 2025-03-24 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='designer_service',
            field=models.BooleanField(default=False),
        ),
    ]
