# Generated by Django 5.1.3 on 2025-03-29 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_alter_product_base_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pending_order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_order', to='store.pendingorder'),
        ),
    ]
