# Generated by Django 5.1.3 on 2025-03-29 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_order_pending_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-date_ordered']},
        ),
        migrations.RenameField(
            model_name='order',
            old_name='total_price',
            new_name='item_price',
        ),
    ]
