# Generated by Django 5.1.3 on 2025-03-29 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_alter_order_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='item_price',
            new_name='total_price',
        ),
    ]
