# Generated by Django 5.1.3 on 2025-03-31 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_design', '0002_templatepayment'),
        ('store', '0030_rename_item_price_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingorder',
            name='user_design',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_design', to='custom_design.userdesign'),
        ),
        migrations.AlterField(
            model_name='pendingorder',
            name='order_type',
            field=models.CharField(choices=[('print', 'Print Only'), ('designer', 'Hire Designer'), ('design', 'Created Design')], default='print', max_length=20),
        ),
    ]
