# Generated by Django 5.1.3 on 2025-03-31 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_design', '0002_templatepayment'),
        ('store', '0031_pendingorder_user_design_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_products', to='custom_design.producttype'),
        ),
    ]
