# Generated by Django 5.1.3 on 2025-04-03 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_product_product_type'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(condition=models.Q(('complete', False)), fields=('customer',), name='unique_incomplete_order_per_customer'),
        ),
    ]
