# Generated by Django 5.1.3 on 2025-04-03 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_order_unique_incomplete_order_per_customer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='order',
            name='unique_incomplete_order_per_customer',
        ),
    ]
