# Generated by Django 5.1.3 on 2025-04-04 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0034_alter_order_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='dimension_unit',
        ),
        migrations.RemoveField(
            model_name='order',
            name='height',
        ),
        migrations.RemoveField(
            model_name='order',
            name='width',
        ),
    ]
