# Generated by Django 5.1.3 on 2025-05-20 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0036_remove_product_category_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bulk_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
