# Generated by Django 5.1.3 on 2025-06-03 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0037_product_bulk_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_2',
            field=models.ImageField(blank=True, help_text='Optional secondary image', null=True, upload_to='product/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_3',
            field=models.ImageField(blank=True, help_text='Optional secondary image', null=True, upload_to='product/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_4',
            field=models.ImageField(blank=True, help_text='Optional secondary image', null=True, upload_to='product/'),
        ),
    ]
