# Generated by Django 5.1.3 on 2025-03-30 18:50

import custom_design.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorPalette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('colors', models.JSONField(help_text='JSON array of hex color codes')),
                ('is_premium', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DesignAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('clipart', 'Clipart'), ('shape', 'Shape'), ('frame', 'Frame'), ('background', 'Background'), ('element', 'Design Element'), ('logo', 'Logo')], max_length=20)),
                ('image', models.ImageField(upload_to=custom_design.models.design_asset_path)),
                ('svg_data', models.TextField(blank=True, help_text='SVG data for vector assets')),
                ('is_premium', models.BooleanField(default=False)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DesignCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Font Awesome icon class', max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
            ],
            options={
                'verbose_name_plural': 'Design Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Font',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('display_name', models.CharField(blank=True, max_length=100)),
                ('font_file', models.FileField(help_text='Upload .ttf, .otf, or .woff file', upload_to='design_fonts/')),
                ('css_url', models.URLField(blank=True, help_text='URL to font CSS if using external font service')),
                ('is_premium', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Font Awesome icon class', max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('default_width', models.IntegerField(default=1800, help_text='Default canvas width in pixels')),
                ('default_height', models.IntegerField(default=1600, help_text='Default canvas height in pixels')),
                ('has_print_area', models.BooleanField(default=True, help_text='Whether this product has defined print areas')),
            ],
            options={
                'verbose_name_plural': 'Product Types',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DesignTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('description', models.TextField(blank=True)),
                ('preview_image', models.ImageField(upload_to=custom_design.models.design_template_path)),
                ('canvas_json', models.JSONField(default=custom_design.models.default_canvas_json, help_text='Fabric.js canvas data in JSON format')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_premium', models.BooleanField(default=False, help_text='Whether this template requires premium access')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='custom_design.designcategory')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='custom_design.producttype')),
            ],
            options={
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('base_image', models.ImageField(help_text='Base product image for customization', upload_to=custom_design.models.product_template_path)),
                ('back_image', models.ImageField(blank=True, help_text='Back image for double-sided products', null=True, upload_to=custom_design.models.product_template_path)),
                ('color_hex', models.CharField(blank=True, help_text='Hex color code for variant', max_length=7)),
                ('price_adjustment', models.DecimalField(decimal_places=2, default=0.0, help_text='Price adjustment relative to base price', max_digits=10)),
                ('is_default', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('print_areas', models.JSONField(blank=True, null=True)),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='custom_design.producttype')),
            ],
            options={
                'ordering': ['product_type', 'name'],
                'unique_together': {('product_type', 'name')},
            },
        ),
        migrations.CreateModel(
            name='UserDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('canvas_json', models.JSONField(help_text='Fabric.js canvas data in JSON format')),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to=custom_design.models.user_design_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_draft', models.BooleanField(default=True)),
                ('design_side', models.CharField(default='front', help_text='Which side of the product this design is for', max_length=20)),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_design.producttype')),
                ('product_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='custom_design.productvariant')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='custom_design.designtemplate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='TemplateTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_ref', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('email', models.EmailField(blank=True, default='default@example.com', max_length=254, null=True)),
                ('amount', models.PositiveIntegerField(default=500)),
                ('is_verified', models.BooleanField(default=False)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_design.designtemplate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'template')},
            },
        ),
    ]
