# Generated by Django 5.1.3 on 2025-03-27 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_design', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designtemplate',
            name='is_premium',
            field=models.BooleanField(default={'background': '#ffffff', 'objects': [], 'version': '5.3.1'}, help_text='Whether this template requires premium access'),
        ),
    ]
