# Generated by Django 5.1.3 on 2025-03-27 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_design', '0002_alter_designtemplate_is_premium'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designtemplate',
            name='canvas_json',
            field=models.JSONField(default={'background': '#ffffff', 'objects': [], 'version': '5.3.1'}, help_text='Fabric.js canvas data in JSON format'),
        ),
        migrations.AlterField(
            model_name='designtemplate',
            name='is_premium',
            field=models.BooleanField(default=False, help_text='Whether this template requires premium access'),
        ),
    ]
