# Generated by Django 5.1.3 on 2025-03-28 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_design', '0003_alter_designtemplate_canvas_json_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttype',
            name='default_height',
            field=models.IntegerField(default=1600, help_text='Default canvas height in pixels'),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='default_width',
            field=models.IntegerField(default=1800, help_text='Default canvas width in pixels'),
        ),
    ]
