# Generated by Django 5.1.3 on 2025-03-29 07:40

import custom_design.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_design', '0004_alter_producttype_default_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designtemplate',
            name='canvas_json',
            field=models.JSONField(default=custom_design.models.default_canvas_json, help_text='Fabric.js canvas data in JSON format'),
        ),
    ]
